export default [
  STRUCTURE_TOWER,
  STRUCTURE_SPAWN,
  STRUCTURE_EXTENSION,
  STRUCTURE_LAB,
  STRUCTURE_NUKER,
  STRUCTURE_POWER_SPAWN,
  STRUCTURE_LINK,
  STRUCTURE_STORAGE,
  STRUCTURE_TERMINAL,
  STRUCTURE_FACTORY,
  STRUCTURE_CONTAINER,
  'any',
]
